import type { CategoryDefinition } from "./types.js";

/**
 * Passidex category schemas — ESPR product groups + Battery Regulation + CPR
 * (construction). Derived from the MVP schema and extended with per-field
 * status metadata (required / suppliedBy) and EU DPP mapping (dppPath).
 *
 * `dppPath` values follow a pragmatic, stable dotted namespace that the Phase 5
 * exporter maps onto GS1 Digital Link link types / EU DPP Registry attributes:
 *   identification.*   — product & actor identifiers
 *   materials.*        — material composition & content
 *   circularity.*      — recycled content, repairability, spare parts
 *   carbon.*           — carbon footprint / GWP
 *   substances.*       — substances of concern
 *   performance.*      — declared performance (CPR)
 *   compliance.*       — declarations, certificates, CE marking
 */
export const CATEGORIES: CategoryDefinition[] = [
  // ---------------------------------------------------------------- ESPR: textile
  {
    key: "textile",
    label: "Tekstil in oblačila",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2027–2028",
    kind: "materials",
    icon: "Shirt",
    fields: [
      {
        key: "material_composition",
        label: "Sestava materialov",
        type: "material_composition",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        help: "Delež posameznih vlaken v %, skupaj ~100 %.",
        dppPath: "materials.composition",
      },
      {
        key: "recycled_content_pct",
        label: "Recikliran delež",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "country_of_origin",
        label: "Država porekla",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "identification.countryOfOrigin",
      },
      {
        key: "svhc_substances",
        label: "Snovi, ki vzbujajo veliko zaskrbljenost (SVHC)",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        help: "Navedba SVHC snovi > 0,1 % (w/w), sicer 'brez'.",
        dppPath: "substances.svhc",
      },
      {
        key: "care_durability",
        label: "Navodila za nego / trajnost",
        type: "string",
        framework: "ESPR",
        required: false,
        suppliedBy: "manufacturer",
        dppPath: "circularity.durability",
      },
    ],
  },

  // -------------------------------------------------------------- ESPR: furniture
  {
    key: "furniture",
    label: "Pohištvo",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2028",
    kind: "materials",
    icon: "Sofa",
    fields: [
      {
        key: "material_composition",
        label: "Sestava materialov",
        type: "material_composition",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "materials.composition",
      },
      {
        key: "recycled_content_pct",
        label: "Recikliran delež",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "country_of_origin",
        label: "Država porekla",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "identification.countryOfOrigin",
      },
      {
        key: "svhc_substances",
        label: "Snovi, ki vzbujajo veliko zaskrbljenost (SVHC)",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "substances.svhc",
      },
    ],
  },

  // ------------------------------------------------------------- ESPR: mattresses
  {
    key: "mattresses",
    label: "Vzmetnice",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2029",
    kind: "materials",
    icon: "Sofa",
    fields: [
      {
        key: "material_composition",
        label: "Sestava materialov",
        type: "material_composition",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "materials.composition",
      },
      {
        key: "recycled_content_pct",
        label: "Recikliran delež",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "foam_density",
        label: "Gostota pene",
        type: "quantity",
        unit: "kg/m³",
        framework: "ESPR",
        required: false,
        suppliedBy: "supplier",
        dppPath: "performance.foamDensity",
      },
      {
        key: "svhc_substances",
        label: "Snovi, ki vzbujajo veliko zaskrbljenost (SVHC)",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "substances.svhc",
      },
    ],
  },

  // ------------------------------------------------------- Battery Reg: batteries
  {
    key: "batteries",
    label: "Baterije",
    framework: "BATTERY_REG",
    frameworkLabel: "Uredba o baterijah (EU) 2023/1542",
    eta: "18. feb 2027",
    kind: "specs",
    icon: "BatteryFull",
    fields: [
      {
        key: "cell_chemistry",
        label: "Kemija celice",
        type: "string",
        framework: "BATTERY_REG",
        required: true,
        suppliedBy: "supplier",
        dppPath: "identification.cellChemistry",
      },
      {
        key: "capacity",
        label: "Kapaciteta",
        type: "quantity",
        unit: "kWh",
        framework: "BATTERY_REG",
        required: true,
        suppliedBy: "supplier",
        dppPath: "performance.ratedCapacity",
      },
      {
        key: "carbon_footprint",
        label: "Ogljični odtis",
        type: "quantity",
        unit: "kg CO₂e/kWh",
        framework: "BATTERY_REG",
        required: true,
        suppliedBy: "supplier",
        dppPath: "carbon.footprintPerKwh",
      },
      {
        key: "recycled_content_crit",
        label: "Recikliran delež (Co/Li/Ni)",
        type: "percentage",
        framework: "BATTERY_REG",
        required: true,
        suppliedBy: "supplier",
        help: "Delež reciklirane kritične surovine (kobalt / litij / nikelj).",
        dppPath: "circularity.recycledCriticalRawMaterials",
      },
    ],
  },

  // ------------------------------------------------------------------ ESPR: tires
  {
    key: "tires",
    label: "Pnevmatike",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2027",
    kind: "specs",
    icon: "CircleDot",
    fields: [
      {
        key: "rolling_resistance",
        label: "Kotalni upor",
        type: "enum",
        options: ["A", "B", "C", "D", "E"],
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "performance.rollingResistanceClass",
      },
      {
        key: "wet_grip",
        label: "Oprijem na mokrem",
        type: "enum",
        options: ["A", "B", "C", "D", "E"],
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "performance.wetGripClass",
      },
      {
        key: "recycled_rubber_pct",
        label: "Recikliran delež gume",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "noise_level",
        label: "Raven hrupa",
        type: "quantity",
        unit: "dB",
        framework: "ESPR",
        required: false,
        suppliedBy: "supplier",
        dppPath: "performance.externalRollingNoise",
      },
    ],
  },

  // ------------------------------------------------------------- ESPR: iron/steel
  {
    key: "iron_steel",
    label: "Jeklo in železo",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2027–2028",
    kind: "specs",
    icon: "Cpu",
    fields: [
      {
        key: "recycled_content_pct",
        label: "Recikliran delež",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "carbon_footprint_a1a3",
        label: "Ogljični odtis (A1–A3)",
        type: "quantity",
        unit: "t CO₂e/t",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "carbon.gwpA1A3",
      },
      {
        key: "ore_origin",
        label: "Poreklo rude",
        type: "string",
        framework: "ESPR",
        required: false,
        suppliedBy: "supplier",
        dppPath: "identification.rawMaterialOrigin",
      },
    ],
  },

  // ------------------------------------------------------------ ESPR: electronics
  {
    key: "electronics",
    label: "Elektronika in IKT",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2028–2029",
    kind: "specs",
    icon: "Cpu",
    fields: [
      {
        key: "repairability_index",
        label: "Indeks popravljivosti",
        type: "quantity",
        unit: "/10",
        framework: "ESPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "circularity.repairabilityScore",
      },
      {
        key: "recycled_plastic_pct",
        label: "Recikliran delež plastike",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "circularity.recycledContentShare",
      },
      {
        key: "energy_class",
        label: "Energijski razred",
        type: "enum",
        options: ["A", "B", "C", "D", "E", "F", "G"],
        framework: "ESPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "performance.energyClass",
      },
      {
        key: "spare_parts_availability",
        label: "Razpoložljivost rezervnih delov",
        type: "quantity",
        unit: "let",
        framework: "ESPR",
        required: false,
        suppliedBy: "manufacturer",
        dppPath: "circularity.sparePartsAvailabilityYears",
      },
    ],
  },

  // ------------------------------------------------------------- ESPR: detergents
  {
    key: "detergents",
    label: "Detergenti in površinsko aktivne snovi",
    framework: "ESPR",
    frameworkLabel: "ESPR",
    eta: "2027",
    kind: "specs",
    icon: "FlaskConical",
    fields: [
      {
        key: "biodegradability",
        label: "Biorazgradljivost",
        type: "string",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        help: "npr. '> 90 % / 28 dni' (OECD 301).",
        dppPath: "performance.biodegradability",
      },
      {
        key: "renewable_surfactant_pct",
        label: "Delež PAS iz obnovljivih virov",
        type: "percentage",
        framework: "ESPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "materials.renewableContentShare",
      },
      {
        key: "concentration",
        label: "Koncentracija",
        type: "string",
        framework: "ESPR",
        required: false,
        suppliedBy: "manufacturer",
        dppPath: "performance.concentration",
      },
    ],
  },

  // ------------------------------------------------------ CPR: doors and windows
  {
    key: "construction_doors",
    label: "Vrata in okna",
    framework: "CPR",
    frameworkLabel: "CPR 2024/3110",
    eta: "~2027–2028 (po delegiranem aktu)",
    kind: "construction",
    icon: "Building2",
    fields: [
      {
        key: "dop_number",
        label: "Št. Declaration of Performance",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.declarationOfPerformance",
      },
      {
        key: "epd_reference",
        label: "EPD referenca (EN 15804)",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "compliance.epdReference",
      },
      {
        key: "gwp_a1a3",
        label: "GWP A1–A3",
        type: "quantity",
        unit: "kg CO₂e/kos",
        framework: "CPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "carbon.gwpA1A3",
      },
      {
        key: "ce_marking",
        label: "CE oznaka",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.ceMarking",
      },
    ],
  },

  // -------------------------------------------------------------- CPR: glass
  {
    key: "construction_glass",
    label: "Gradbeno steklo",
    framework: "CPR",
    frameworkLabel: "CPR 2024/3110",
    eta: "~2027–2028",
    kind: "construction",
    icon: "Building2",
    fields: [
      {
        key: "dop_number",
        label: "Št. Declaration of Performance",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.declarationOfPerformance",
      },
      {
        key: "epd_reference",
        label: "EPD referenca (EN 15804)",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "compliance.epdReference",
      },
      {
        key: "gwp_a1a3",
        label: "GWP A1–A3",
        type: "quantity",
        unit: "kg CO₂e/m²",
        framework: "CPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "carbon.gwpA1A3",
      },
      {
        key: "ce_marking",
        label: "CE oznaka",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.ceMarking",
      },
    ],
  },

  // -------------------------------------------------------- CPR: other products
  {
    key: "construction_other",
    label: "Drugi gradbeni proizvodi",
    framework: "CPR",
    frameworkLabel: "CPR 2024/3110",
    eta: "fazno do 2032",
    kind: "construction",
    icon: "Building2",
    fields: [
      {
        key: "dop_number",
        label: "Št. Declaration of Performance",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.declarationOfPerformance",
      },
      {
        key: "epd_reference",
        label: "EPD referenca (EN 15804)",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "supplier",
        dppPath: "compliance.epdReference",
      },
      {
        key: "gwp_a1a3",
        label: "GWP A1–A3",
        type: "quantity",
        unit: "kg CO₂e",
        framework: "CPR",
        required: false,
        suppliedBy: "supplier",
        dppPath: "carbon.gwpA1A3",
      },
      {
        key: "ce_marking",
        label: "CE oznaka",
        type: "cert_ref",
        framework: "CPR",
        required: true,
        suppliedBy: "manufacturer",
        dppPath: "compliance.ceMarking",
      },
    ],
  },
];
